'use client'

import { Activity, Bell, CheckCircle2, ChevronRight, Clock3, Trophy } from 'lucide-react'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import InternshipShell from '@/components/InternshipShell'
import { defaultInternshipState, internshipPrograms, internshipStorageKey } from '@/lib/internship'

const recommended = [
  { title: 'Full Stack Development', image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=700&h=380&fit=crop&auto=format' },
  { title: 'Product Design Systems', image: 'https://images.unsplash.com/photo-1559028012-481c04fa702d?w=700&h=380&fit=crop&auto=format' },
  { title: 'Modern Data Workflows', image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=700&h=380&fit=crop&auto=format' },
]

export default function InternshipDashboardPage() {
  const [state, setState] = useState(defaultInternshipState)
  useEffect(() => { const saved = window.localStorage.getItem(internshipStorageKey); if (saved) setState({ ...defaultInternshipState, ...JSON.parse(saved) }) }, [])
  const program = internshipPrograms.find((item) => item.slug === state.programSlug)
  const assessmentLabel = state.assessmentStatus === 'UNDER_REVIEW' ? 'Submitted · Under review' : state.assessmentStatus === 'OBJECTIVE_SUBMITTED' ? 'Theory in progress' : state.assessmentStatus === 'IN_PROGRESS' ? 'In progress' : state.paymentStatus === 'PAID' ? 'Not started' : 'Locked / pending'
  return (
    <InternshipShell>
      <div className="space-y-5">
        {program ? <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_8px_24px_rgba(28,29,82,0.09)] sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-[#5FBB46]">{program.name}</p><h1 className="mt-2 text-lg font-bold text-[#1C1D52]">Your internship application</h1><p className="mt-1 text-xs text-slate-500">Payment: <strong className={state.paymentStatus === 'PAID' ? 'text-[#5FBB46]' : 'text-amber-600'}>{state.paymentStatus === 'PAID' ? 'Paid' : 'Pending'}</strong> · Assessment: <strong className="text-[#1C1D52]">{assessmentLabel}</strong></p></div>{state.paymentStatus !== 'PAID' ? <Link href="/internship/payment" className="rounded-lg bg-[#5FBB46] px-4 py-2.5 text-center text-xs font-bold text-[#14204f]">Complete payment</Link> : state.assessmentStatus !== 'UNDER_REVIEW' ? <Link href="/internship/assessment/readiness" className="rounded-lg bg-[#5FBB46] px-4 py-2.5 text-center text-xs font-bold text-[#14204f]">{state.assessmentStatus === 'IN_PROGRESS' ? 'Continue assessment' : 'Start assessment'}</Link> : <span className="rounded-lg bg-[#e8f7eb] px-4 py-2.5 text-center text-xs font-bold text-[#397d3a]">Outcome under review</span>}</div></section> : <section className="rounded-2xl bg-[#1C1D52] p-6 text-white"><h1 className="text-xl font-bold">Start your internship journey</h1><p className="mt-2 text-xs text-white/70">Choose an internship plan to begin your application.</p><Link href="/internship/enroll" className="mt-4 inline-flex rounded-lg bg-[#5FBB46] px-4 py-2.5 text-xs font-bold text-[#14204f]">View internship plans</Link></section>}
        <section className="rounded-2xl bg-white p-5 shadow-[0_8px_24px_rgba(28,29,82,0.09)] sm:p-6">
          <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold text-[#5FBB46]">Software Development · Intermediate</p><p className="mt-3 text-xs text-slate-500">Week 4 of 12 · Start Date: Aug 17, 2026 · Expected Completion: Nov 9, 2026</p></div><span className="text-xs font-bold text-[#5FBB46]">33%</span></div>
          <div className="mt-4"><div className="flex items-center justify-between text-xs font-bold text-[#1C1D52]"><span>Progress</span></div><div className="mt-2 h-1.5 rounded-full bg-[#E7EEF8]"><div className="h-full w-1/3 rounded-full bg-[#5FBB46]" /></div></div>
        </section>

        <section className="grid gap-4 sm:grid-cols-3">
          {[{ label: 'Completed tasks', value: '12', icon: CheckCircle2 }, { label: 'Average grade', value: '84%', icon: Trophy }, { label: 'Pending tasks', value: '2', icon: Activity }].map(({ label, value, icon: Icon }) => <div key={label} className="rounded-2xl bg-white p-5 shadow-[0_8px_24px_rgba(28,29,82,0.09)]"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#e8f7eb] text-[#5FBB46]"><Icon className="h-4 w-4" /></span><strong className="mt-3 block text-xl text-[#1C1D52]">{value}</strong><span className="mt-1 block text-xs text-slate-500">{label}</span></div>)}
        </section>

        <section className="rounded-2xl bg-[#5FBB46] p-5 text-white shadow-[0_12px_28px_rgba(95,187,70,0.18)] sm:p-6"><h1 className="text-xl font-bold">Week 4 - Frontend Development</h1><p className="mt-2 text-xs text-white/80">Build a responsive dashboard using React and TypeScript.</p><div className="mt-4 flex flex-wrap gap-4 text-xs text-white/90"><span className="flex items-center gap-1"><Clock3 className="h-3.5 w-3.5" />Due: Tomorrow, 11:59 PM</span><span className="flex items-center gap-1"><Activity className="h-3.5 w-3.5" />In Progress</span></div></section>

        <section className="flex flex-col gap-4 rounded-2xl bg-white p-5 shadow-[0_8px_24px_rgba(28,29,82,0.09)] sm:flex-row sm:items-center sm:justify-between sm:p-6"><div className="flex items-center gap-3"><div className="h-11 w-11 rounded-full bg-slate-200" /><div><h2 className="text-sm font-bold text-[#1C1D52]">Your Mentor</h2><p className="mt-1 text-xs text-slate-500">John Doe · Senior Software Engineer</p><p className="mt-1 text-xs font-semibold text-[#5FBB46]">● Available</p><p className="mt-1 text-[10px] text-slate-500">Next meeting: Thursday, Sep 10 · 4:00 PM</p></div></div><div className="flex gap-2 sm:flex-col"><button type="button" className="rounded-lg bg-[#5FBB46] px-4 py-2 text-xs font-semibold text-white">Message Mentor</button><button type="button" className="rounded-lg px-4 py-2 text-xs font-semibold text-[#5FBB46] shadow-[inset_0_0_0_1px_#5FBB46]">View Profile</button></div></section>
          <section className="flex flex-col gap-4 rounded-2xl bg-white p-5 shadow-[0_8px_24px_rgba(28,29,82,0.09)] sm:flex-row sm:items-center sm:justify-between sm:p-6"><div className="flex items-center gap-3"><div className="h-11 w-11 rounded-full bg-slate-200" /><div><h2 className="text-sm font-bold text-[#1C1D52]">Your Mentor</h2><p className="mt-1 text-xs text-slate-500">John Doe · Senior Software Engineer</p><p className="mt-1 text-xs font-semibold text-[#5FBB46]">● Available</p><p className="mt-1 text-[10px] text-slate-500">Next meeting: Thursday, Sep 10 · 4:00 PM</p></div></div><div className="flex gap-2 sm:flex-col"><Link href="/internship/dashboard/mentor" className="rounded-lg bg-[#5FBB46] px-4 py-2 text-center text-xs font-semibold text-white">Message Mentor</Link><Link href="/internship/dashboard/mentor" className="rounded-lg px-4 py-2 text-center text-xs font-semibold text-[#5FBB46] shadow-[inset_0_0_0_1px_#5FBB46]">View Profile</Link></div></section>

        <section className="rounded-2xl bg-white p-5 shadow-[0_8px_24px_rgba(28,29,82,0.09)] sm:p-6"><div className="flex items-center justify-between"><h2 className="text-sm font-bold text-[#1C1D52]">Recent Feedback</h2><a href="#feedback" className="text-xs font-semibold text-[#5FBB46]">View Submission <ChevronRight className="inline h-3 w-3" /></a></div><h3 className="mt-4 text-xs font-bold text-[#1C1D52]">Task: Responsive Dashboard</h3><p className="mt-2 text-xs text-slate-500"><span className="font-bold text-[#5FBB46]">★ Score: 92%</span> · Mentor: John Doe</p><p className="mt-2 text-xs leading-5 text-slate-500">Great implementation. Your component structure is clean. Improve accessibility on the navigation buttons.</p><p className="mt-2 text-[10px] text-slate-400">2 hours ago</p></section>

        <section className="rounded-2xl bg-white p-5 shadow-[0_8px_24px_rgba(28,29,82,0.09)] sm:p-6"><h2 className="text-sm font-bold text-[#1C1D52]">Announcements</h2><div className="mt-4 space-y-3">{['New group project guidelines', 'Mentor session scheduled', 'Week 5 resources are now available'].map((item, index) => <div key={item} className="flex items-start gap-3"><span className="mt-0.5 flex h-5 w-5 items-center justify-center rounded-full bg-[#e8f7eb] text-[#5FBB46]"><Bell className="h-3 w-3" /></span><div><p className="text-xs font-semibold text-[#1C1D52]">{item}</p><p className="text-[10px] text-slate-500">Posted {index === 0 ? '2 hours ago' : index === 1 ? 'yesterday' : '2 days ago'}</p></div></div>)}</div><a href="#announcements" className="mt-5 inline-block text-xs font-semibold text-[#5FBB46]">View all announcements →</a></section>

        <section><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-bold text-[#1C1D52]">Recommended Courses</h2><a href="/courses" className="text-xs font-semibold text-[#5FBB46]">See More <ChevronRight className="inline h-3 w-3" /></a></div><div className="grid gap-4 md:grid-cols-3">{recommended.map((course) => <article key={course.title} className="overflow-hidden rounded-2xl bg-white p-2 shadow-[0_8px_24px_rgba(28,29,82,0.09)]"><Image src={course.image} alt="" width={700} height={380} className="h-28 w-full rounded-xl object-cover" /><div className="p-2"><span className="rounded bg-[#e8f7eb] px-2 py-1 text-[9px] font-bold text-[#5FBB46]">POPULAR</span><h3 className="mt-3 text-xs font-bold text-[#1C1D52]">{course.title}</h3><p className="mt-2 text-[10px] leading-4 text-slate-500">Laravel is a PHP based web framework for building high-end enterprise grade backends.</p><button type="button" className="mt-4 w-full rounded-lg bg-[#5FBB46] py-2 text-xs font-semibold text-white">Enroll Now</button></div></article>)}</div></section>
      </div>
    </InternshipShell>
  )
}
