'use client'

import Image from 'next/image'
import { Download, Eye, X } from 'lucide-react'
import { useState } from 'react'

const certificates = [
  { id: '2026-00847', title: 'Full Stack Development', date: 'August 30, 2026' },
  { id: '2026-00431', title: 'Introduction to UI/UX Design', date: 'June 12, 2026' },
  { id: '2026-00120', title: 'Laravel Backend Essentials', date: 'April 18, 2026' },
]

function Certificate({ title, date, id }: { title: string; date: string; id: string }) {
  return <div className="certificate-print relative min-h-[580px] overflow-hidden border-[10px] border-[#1C1D52] bg-white p-5 text-[#1C1D52] shadow-xl sm:min-h-[680px] sm:p-10"><div className="absolute inset-3 border-2 border-[#f3b619] sm:inset-5" /><div className="relative flex h-full min-h-[530px] flex-col justify-between border border-[#d9b443]/50 p-5 text-center sm:min-h-[600px] sm:p-10"><div><Image src="/logo.png" alt="Grouh Academy" width={170} height={45} className="mx-auto h-auto w-36 sm:w-44" /><p className="mt-6 text-[10px] font-bold uppercase tracking-[0.32em] text-[#5FBB46] sm:text-xs">Official certification</p><h2 className="mt-8 font-serif text-3xl font-semibold sm:text-5xl">Certificate of Completion</h2><p className="mt-8 text-xs text-slate-500 sm:text-sm">This certificate is proudly presented to</p><h3 className="mt-4 inline-block border-b-2 border-[#f3b619] px-6 pb-3 font-serif text-2xl font-semibold sm:text-4xl">Emmanuel Aster</h3><p className="mx-auto mt-7 max-w-xl text-xs leading-6 text-slate-500 sm:text-sm">For successfully completing the advanced industry certification curriculum and demonstrating mastery of professional standards in</p><p className="mt-5 text-lg font-bold text-[#5FBB46] sm:text-2xl">{title}</p><p className="mt-4 text-xs text-slate-500 sm:text-sm">Completed on {date}</p></div><div className="grid gap-5 text-left text-[9px] text-slate-500 sm:grid-cols-3 sm:items-end"><div><p className="font-serif text-base text-[#1C1D52]">Emmanuel Thomas</p><div className="mt-1 border-t border-slate-300 pt-1 uppercase tracking-wider">Academy Director</div></div><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full border-2 border-[#f3b619] bg-[#ffc32b] text-xl text-white">★</div><div className="text-left sm:text-right">Certificate No: <strong>{id}</strong><br />Verification ID: <strong>VR-7X9K2M44</strong></div></div></div></div>
}
export default function CertificatesPage() {
  const [selected, setSelected] = useState(certificates[0])
  const [online, setOnline] = useState(false)
  return <div className="space-y-6"><section className="rounded-2xl bg-[#5FBB46] px-6 py-6 text-[#14204f] shadow-[0_12px_28px_rgba(95,187,70,0.18)] sm:px-8 sm:py-7"><h1 className="text-3xl font-bold tracking-tight">Certificate System</h1><p className="mt-2 max-w-3xl text-sm leading-5 text-[#14204f]/75">Your official credentials are ready to view online and print as polished PDF certificates.</p></section><section><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-bold text-[#1C1D52]">Currently Selected Certificate</h2><div className="flex gap-2"><button type="button" onClick={() => setOnline(true)} className="inline-flex items-center gap-2 rounded-lg border border-[#1C1D52] px-3 py-2 text-[10px] font-bold text-[#1C1D52]"><Eye className="h-3.5 w-3.5" />View Online</button><button type="button" onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-lg bg-[#1C1D52] px-3 py-2 text-[10px] font-bold text-white"><Download className="h-3.5 w-3.5" />Download PDF</button></div></div><Certificate {...selected} /></section><section className="rounded-2xl bg-white p-5 shadow-[0_8px_24px_rgba(28,29,82,0.09)] sm:p-6"><h2 className="text-sm font-bold text-[#1C1D52]">Your Earned Credentials</h2><div className="mt-4 space-y-2">{certificates.map((certificate) => <div key={certificate.id} className="flex flex-col gap-3 rounded-xl bg-[#fbfcff] p-3 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="text-xs font-bold text-[#1C1D52]">{certificate.title}</h3><p className="mt-1 text-[9px] text-slate-500">Completed on {certificate.date} · ID: CERT-{certificate.id}</p></div><div className="flex gap-2"><button type="button" onClick={() => { setSelected(certificate); setOnline(true) }} className="rounded-lg bg-white px-3 py-2 text-[10px] font-semibold text-[#1C1D52] shadow-[inset_0_0_0_1px_#1C1D52]">View Online</button><button type="button" onClick={() => { setSelected(certificate); window.setTimeout(() => window.print(), 0) }} className="rounded-lg bg-[#1C1D52] px-3 py-2 text-[10px] font-semibold text-white">Download PDF</button></div></div>)}</div></section>{online && <div className="fixed inset-0 z-50 overflow-y-auto bg-[#1C1D52]/70 p-4 sm:p-8"><div className="mx-auto max-w-4xl"><div className="mb-3 flex justify-end"><button type="button" onClick={() => setOnline(false)} className="rounded-full bg-white p-2 text-[#1C1D52]" aria-label="Close certificate preview"><X className="h-5 w-5" /></button></div><Certificate {...selected} /></div></div>}</div>
}
